# The MIT License (MIT)
#
# SPDX-FileCopyrightText: Copyright (c) 2022-2025 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
architect:
  - yegor256
docker:
  image: yegor256/rultor-java
assets:
  settings.xml: yegor256/objectionary-secrets#settings.xml
  pubring.gpg: yegor256/objectionary-secrets#pubring.gpg
  secring.gpg: yegor256/objectionary-secrets#secring.gpg
install: |
  pdd --file=/dev/null
merge:
  script: |
    mvn clean install -Pqulice --errors -Dstyle.color=never
release:
  pre: false
  # yamllint disable rule:line-length
  script: |-
    [[ "${tag}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] || exit -1
    mvn versions:set "-DnewVersion=${tag}" -Dstyle.color=never
    git commit -am "${tag}"
    mvn clean install -Dinvoker.skip
    export MAVEN_OPTS="--add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang.reflect=ALL-UNNAMED"
    mvn clean deploy -Pobjectionary -Psonatype --errors --settings ../settings.xml -Dstyle.color=never
